church_name: Freie-Baptisten Gemeinde Neutraubling
church_logo_image_path: /assets/img/logo.jpg
church_logo2_image_path: /assets/img/logo.jpg
main_image: /uploads/background3.jpg
phone: 0151 / 19415311
church_email: bkjradank@gmail.com
facebook: 'https://www.facebook.com/hartwellbaptistchurch'
twitter: 'https://twitter.com/DrKeithTaylorSr'
youtube:
address: Waldenburger Str. 9
address2:
City: Neutraubling
State: 
Zip: '93073'
services:
  - name: Gottesdienst
    when: 10.00 Uhr
    day: Sonntag
  - name: Bibelstunde
    when: 18.30 Uhr
    day: Donnerstag
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/hartwell.jpg
lattitude: '48.99105'
longitude: '12.20019'
map_zoom_level: 14
Google_calendar_id: leonhart4@gmail.com